// Code generated by mockery v2.6.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UserRetentionCalculator is an autogenerated mock type for the UserRetentionCalculator type
type UserRetentionCalculator struct {
	mock.Mock
}

// Calculate provides a mock function with given fields: rawUsersActivity
func (_m *UserRetentionCalculator) Calculate(rawUsersActivity [][]string) (map[int][]int, error) {
	ret := _m.Called(rawUsersActivity)

	var r0 map[int][]int
	if rf, ok := ret.Get(0).(func([][]string) map[int][]int); ok {
		r0 = rf(rawUsersActivity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int][]int)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([][]string) error); ok {
		r1 = rf(rawUsersActivity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
